### ISSUE TITLE
[explore-v2] setup for beta testing

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#1643]
- [x] send email to beta users
- [x] add line to config.py `EXPLORE_V2_BETA_USERS = []`
- [x] in views.py, send v2 beta users through v2 path
- [x] update chef config with EXPLORE_V2_BETA_USERS list

**Comment by ascott** [comment]
adds config for v2 beta users 
https://github.com/airbnb/superset/pull/1671

**Comment by ascott** [comment]
chef PR https://git.musta.ch/airbnb/chef/pull/13591

**Comment by ascott** [comment]
https://github.com/airbnb/superset/pull/1671
