### ISSUE TITLE
DisplayQueryButton({query})－parameter "query" is empty

### ISSUE THREAD

**Issue by JessicaDuan** [airbnb/superset#2024]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.2

### Expected results
![image](https://cloud.githubusercontent.com/assets/21305317/22240797/86b4a8b8-e257-11e6-8ddf-0fb046257909.png)
Press the button query and we can see the queryString.

### Actual results
The modal dialog shows nothing.

### Steps to reproduce
npm install
npm run prod
python setup.py install

-------------------
Caused by:
1. superset/superset/assets/javascripts/explore/components/ExploreActionButtons.jsx
![image](https://cloud.githubusercontent.com/assets/21305317/22240992/7074db4e-e258-11e6-8878-4f0bdcce8dd0.png)
2. superset/superset/assets/javascripts/explore/explore.jsx
![image](https://cloud.githubusercontent.com/assets/21305317/22240935/3083dd46-e258-11e6-8960-70c1ffba4447.png)
Actually the parameter "query" is not passed.

**Comment by xrmx** [comment]
Looks like a dup of #2006 no?

**Comment by bkyryliuk** [comment]
is fixed in the explore V2

**Comment by ascott** [comment]
yes, this is fixed in V2 and @vera-liu just added a fix for V1 https://github.com/airbnb/superset/pull/2080
