### ISSUE TITLE
Graph never loads (infinite spinner) when using a Result Filter in some cases

### ISSUE THREAD

**Issue by seanabraham** [airbnb/superset#2074]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
* Where can I find this in the production version?
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

Where can I find this?

### Expected results

Graph with a Result filter appears appropriately

### Actual results

Infinite spinner

### Steps to reproduce

Open graph such as http://panoramix.d.musta.ch/r/13513 and notice that there is an infinite spinner / it loads indefinitely. Remove the result filter and re-query, notice the graph returns as expected.

**Comment by vera-liu** [comment]
https://github.com/airbnb/superset/pull/2075
